name: Workflow-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TRAIN_DATASET: "dataset/train_dataset.csv"
  TEST_DATASET: "dataset/test_dataset.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Check Env Variables
      - name: Check Env
        run: |
          echo "Train Dataset: $TRAIN_DATASET"
          echo "Test Dataset: $TEST_DATASET"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Run MLflow project
      - name: Run mlflow project
        run: |
          mlflow run MLProject \
            -P n_estimators=505 \
            -P max_depth=35 \
            -P train_dataset=$TRAIN_DATASET \
            -P test_dataset=$TEST_DATASET \
            --env-manager=local

      # Step 1: Track mlruns with Git LFS and commit .gitattributes
      - name: Track mlruns with Git LFS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git lfs install
          git lfs track "mlruns/**" || true
          git add .gitattributes || true

          # set remote dengan token agar bot bisa push
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          if ! git diff --cached --quiet; then
            git commit -m "Track mlruns with Git LFS"
            git push origin main
          else
            echo "No changes to commit"
          fi

      # Step 2: Commit dan push mlruns hasil run MLflow
      - name: Save mlruns from CI run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mlruns/ || true

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          if ! git diff --cached --quiet; then
            git commit -m "Save mlruns from CI run"
            git push origin main
          else
            echo "No changes to commit"
          fi
